# This workflow will set up Python 3.9, create a Python virtual environment
# install requirements.txt, and run some unit tests

name: unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Create virtual environment
        run: python3 -m venv venv
        run: .\venv\Scripts\activate

      - name: Install requirements.txt
        run: pip3 install -r requirements.txt
      - name: Run pytests
        run: pytest
        